import { type Command } from './orchestrator.model.js';

const APPROVE_VERBS = new Set(['approve', 'approved', 'lgtm', 'ship', 'go']);
const CANCEL_VERBS = new Set(['cancel', 'stop', 'abort']);
const REVISE_VERBS = new Set(['revise', 'iterate', 'change', 'update']);

/**
 * Parses a `<prefix> <verb> [text]` command out of a comment body. Returns
 * { kind: 'none' } when no command line is present — callers treat that as plan
 * iteration feedback.
 */
export function parseCommand(body: string, prefix: string): Command {
  const lower = prefix.toLowerCase();
  for (const raw of body.split('\n')) {
    const line = raw.trim();
    if (!line.toLowerCase().startsWith(lower)) {
      continue;
    }
    const rest = line.slice(prefix.length).trim();
    const [verb = '', ...args] = rest.split(/\s+/);
    const v = verb.toLowerCase();
    if (APPROVE_VERBS.has(v)) {
      return { kind: 'approve' };
    }
    if (CANCEL_VERBS.has(v)) {
      return { kind: 'cancel' };
    }
    if (v === 'status') {
      return { kind: 'status' };
    }
    if (REVISE_VERBS.has(v)) {
      return { kind: 'revise', text: args.join(' ') };
    }
    return { kind: 'none' };
  }
  return { kind: 'none' };
}

/** Best-effort extraction of the "Acceptance criteria" section from a plan. */
export function acceptanceCriteria(plan: string): string | undefined {
  const match = plan.match(/##\s*Acceptance criteria\s*\n([\s\S]*?)(?:\n##\s|\s*$)/i);
  return match ? match[1].trim() : undefined;
}

export function implementCommitMessage(
  issueNumber: number,
  title: string,
  attempt: number,
): string {
  return (
    `feat: resolve #${issueNumber} ${title}`.slice(0, 72) +
    (attempt > 1 ? ` (attempt ${attempt})` : '')
  );
}

export function reviseCommitMessage(pass: number): string {
  return `fix: address review findings (pass ${pass})`;
}

export interface PrBodyInput {
  issueNumber: number;
  plan: string;
  confidence: number | null;
  threshold: number;
  meetsThreshold: boolean;
  unresolvedIssues?: string;
}

export function buildPrBody(input: PrBodyInput): string {
  const lines = [
    `This pull request was generated by **Hermes Agent** to resolve #${input.issueNumber}.`,
    '',
    `Closes #${input.issueNumber}`,
    '',
    '## Plan',
    input.plan.trim(),
    '',
    '## Self-review',
    `Confidence: ${input.confidence ?? 'n/a'}/100 (threshold ${input.threshold}).`,
  ];
  if (input.meetsThreshold) {
    lines.push('All automated review checks passed.');
  } else {
    lines.push(
      'Opened below the confidence threshold for human attention. Unresolved findings:',
      '',
      input.unresolvedIssues ?? '(none recorded)',
    );
  }
  lines.push('', '---', '🤖 Draft PR generated by Hermes Agent — review before merging.');
  return lines.join('\n');
}
